import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`text-foreground bg-background antialiased hide-scrollbar ${inter.className} flex flex-col min-h-screen`}
      >
        <Providers>
          <Header />
          <main className="flex-grow">{children}</main> {/* This ensures the content area grows */}
          <Footer /> {/* Footer always at the bottom */}
        </Providers>
      </body>
    </html>
  );
}
